### ISSUE TITLE
Proposal: Add a section for valid and invalide url patterns

### ISSUE THREAD

**Issue by gabiBrysch** [Haufe-Lexware/api-style-guide#11]
within Aka-I we discussed valid and invalid url patterns regarding collection resources and query parameters, we decided this way p.e. collection for users
- to retrieve a list both urls, with and without trailing slash is valid:  /users and /users/
- to retrieve a list filtered with further query params, only the variant /users?offset=<value> is valid, not the variant with the combination "/?" /users/?offset=<value> in it, because the "?" gets interpreted as a further (id) value.

**Comment by Kodrafo** [comment]
I added it to the uri components, I will inform you when I published it.
