### ISSUE TITLE
Rework of API Styleguide to clearly state preferences

### ISSUE THREAD

**Issue by hlgr360** [Haufe-Lexware/api-style-guide#8]
Currently the API style guide reads as a cross between education and wish list. But our intent is that this style guide provides the default preference for our API design and development process. And this means making choices.
We should add a preamble stating that Haufe.Group teams can deviate from the style guide if they provide the arguments justifying it.

**Comment by Kodrafo** [comment]
Please review https://github.com/Haufe-Lexware/api-style-guide/blob/master/readme.md and give feedback
